apiVersion: v1
kind: PersistentVolume
metadata:
  name: [myPersistentVolumeName]
  # labels:
  #   storage: slow
spec:
  capacity:
    storage: [myPersistentVolumeCapacity]
  accessModes:
  - ReadWriteOnce
  storageClassName: [myStorageClassName]
  azureFile:
    secretName: [mySecretName]
    shareName: [myFileShareName]
    readOnly: false
