version: '3.2'
services:
    scheduler:
        build: .
        image: stefanofioravanzo/mxnet-cifar10-dist:cpu
        container_name: scheduler
        env_file: .scheduler_env
        networks:
            - mxnetwork
        volumes: &cifarvol
            - /Users/StefanoFiora/Work/Datasets/cifar-10/data/cifar:/data/cifar
            - .:/app
    server:
        build: .
        image: stefanofioravanzo/mxnet-cifar10-dist:cpu
        container_name: server
        env_file: .server_env
        depends_on:
            - scheduler
        networks:
            - mxnetwork
        volumes: *cifarvol
    worker:
        build: .
        image: stefanofioravanzo/mxnet-cifar10-dist:cpu
        env_file: .worker_env
        depends_on:
            - server
        networks:
            - mxnetwork
        volumes: *cifarvol
networks:
    mxnetwork:
